### ISSUE TITLE
Availability of csv files

### ISSUE THREAD

**Issue by davidshumway** [rtsearcy/wq-models-high-frequency-data#1]
Thanks for sharing this repository and associated datasets! Just a few questions on data.

In terms of data collection:

What is an example of airports.csv?
https://github.com/rtsearcy/wq-models-high-frequency-data/blob/2b0af2de648eeb2e78749402dd9ba1432baa0822/Collect_Data/getMet_NCDC.py#L16

Are any of the EDA datasets available, such as:

Lovers_Point_variables_fib.csv
https://github.com/rtsearcy/wq-models-high-frequency-data/blob/2b0af2de648eeb2e78749402dd9ba1432baa0822/EDA/HF_EDA_dataset_combo.py#L43

LP_hf_modeling_dataset_20130420 / 15 / 18
https://github.com/rtsearcy/wq-models-high-frequency-data/blob/2b0af2de648eeb2e78749402dd9ba1432baa0822/EDA/HF_EDA_dataset_combo.py#L49

CUTI_daily.csv
https://github.com/rtsearcy/wq-models-high-frequency-data/blob/2b0af2de648eeb2e78749402dd9ba1432baa0822/EDA/HF_EDA_dataset_combo.py#L24

full_moon.csv
https://github.com/rtsearcy/wq-models-high-frequency-data/blob/2b0af2de648eeb2e78749402dd9ba1432baa0822/EDA/HF_EDA_dataset_combo.py#L101

logistics_all_events.csv (EDA/model development)
https://github.com/rtsearcy/wq-models-high-frequency-data/blob/2b0af2de648eeb2e78749402dd9ba1432baa0822/Model_Development/HF_predictive_models.py#L96
https://github.com/rtsearcy/wq-models-high-frequency-data/blob/2b0af2de648eeb2e78749402dd9ba1432baa0822/EDA/HF_EV_stats_plots.py#L73

Are any of the original HF and RM datasets still available?

And in terms of model development and testing:

What is an example of test_cases.csv? Is it generated elsewhere in the program?
https://github.com/rtsearcy/wq-models-high-frequency-data/blob/2b0af2de648eeb2e78749402dd9ba1432baa0822/Model_Development/HF_model_all.py#L77
https://github.com/rtsearcy/wq-models-high-frequency-data/blob/2b0af2de648eeb2e78749402dd9ba1432baa0822/Model_Testing/HF_model_predictions_obs.py#L52
https://github.com/rtsearcy/wq-models-high-frequency-data/blob/2b0af2de648eeb2e78749402dd9ba1432baa0822/Model_Testing/HF_analyze_all_models.py#L74

Thanks!

**Comment by rtsearcy** [comment]
Hi David,

Thank you for your interest in this project, and thank you as well for bearing with the amateur codebase. Here are the files you requested...as this was an academic exercise, you've noticed that a lot of these files are hard coded and site specific. I'd be happy to have a conversation about anything else you're wondering about. Thanks!

Ryan

[airports_all.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793677/airports_all.csv)

[Lovers_Point_variables_fib.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793666/Lovers_Point_variables_fib.csv)

[LP_hf_modeling_dataset_20180421.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793662/LP_hf_modeling_dataset_20180421.csv)
[LP_hf_modeling_dataset_20160409.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793663/LP_hf_modeling_dataset_20160409.csv)
[LP_hf_modeling_dataset_20130420.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793664/LP_hf_modeling_dataset_20130420.csv)

[CUTI_daily.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793671/CUTI_daily.csv)
[full_moon.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793672/full_moon.csv)

[logistics_all_events.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793676/logistics_all_events.csv)

[test_cases.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793658/test_cases.csv)

[all_event_data_CB.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793654/all_event_data_CB.csv)
[all_event_data_LP.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793655/all_event_data_LP.csv)
[all_event_data_HSB.csv](https://github.com/rtsearcy/wq-models-high-frequency-data/files/8793653/all_event_data_HSB.csv)
